name: synesthetix
favicon: null
layout_spectrum: 0.48883219389244914
typography_spectrum: 0.6755457075778395
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.22590315714478493
  lightness: 0.8966704567428678
  saturation: 0.8678491718601435
  rhythmicContrast: 0.3566276072524488
purpose: []
